[theme]

base = "light"

# Primary accent color for interactive elements
primaryColor = "#527570"

# Background color for the main content area
backgroundColor = "#FDFAF1"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#FFFFFF"

# Color used for almost all text
textColor = "#31333F"

# Font family for all text in the app, except code blocks
font = "Rubik, Roboto, sans-serif"